
language: python
python:
  3.6

cache: bundler

script:
  make build

before_deploy:
  mv .jupyter-book/_build .
  cd _build

deploy:
  provider: pages
  skip_cleanup: true
  api_key: 
    secure: $GITHUB_TOKEN
  on: 
    branch: master
