
language: python
python:
  3.6

script:
  make build

before_deploy:
  cd .jupyter-book/_build

deploy:
  provider: pages
  skip_cleanup: true
  api_key: 
    secure: $GITHUB_TOKEN
  on: 
    branch: master
