
language: python
python:
  3.6

cache: bundler

script:
  make build

before_deploy:
  cd .jupyter-book/_build 

deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  on: 
    branch: master
